import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const AIWORK_ENGINE_EXPERIMENTAL = truthy("AIWORK_ENGINE_EXPERIMENTAL")
const AIWORK_ENGINE_DISABLE_CLAUDE_CODE = truthy("AIWORK_ENGINE_DISABLE_CLAUDE_CODE")
const AIWORK_ENGINE_DISABLE_CLAUDE_CODE_SKILLS =
  AIWORK_ENGINE_DISABLE_CLAUDE_CODE || truthy("AIWORK_ENGINE_DISABLE_CLAUDE_CODE_SKILLS")
const copy = process.env["AIWORK_ENGINE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  AIWORK_ENGINE_AUTO_SHARE: truthy("AIWORK_ENGINE_AUTO_SHARE"),
  AIWORK_ENGINE_AUTO_HEAP_SNAPSHOT: truthy("AIWORK_ENGINE_AUTO_HEAP_SNAPSHOT"),
  AIWORK_ENGINE_GIT_BASH_PATH: process.env["AIWORK_ENGINE_GIT_BASH_PATH"],
  AIWORK_ENGINE_CONFIG: process.env["AIWORK_ENGINE_CONFIG"],
  AIWORK_ENGINE_CONFIG_CONTENT: process.env["AIWORK_ENGINE_CONFIG_CONTENT"],
  AIWORK_ENGINE_DISABLE_AUTOUPDATE: truthy("AIWORK_ENGINE_DISABLE_AUTOUPDATE"),
  AIWORK_ENGINE_ALWAYS_NOTIFY_UPDATE: truthy("AIWORK_ENGINE_ALWAYS_NOTIFY_UPDATE"),
  AIWORK_ENGINE_DISABLE_PRUNE: truthy("AIWORK_ENGINE_DISABLE_PRUNE"),
  AIWORK_ENGINE_DISABLE_TERMINAL_TITLE: truthy("AIWORK_ENGINE_DISABLE_TERMINAL_TITLE"),
  AIWORK_ENGINE_SHOW_TTFD: truthy("AIWORK_ENGINE_SHOW_TTFD"),
  AIWORK_ENGINE_PERMISSION: process.env["AIWORK_ENGINE_PERMISSION"],
  AIWORK_ENGINE_DISABLE_DEFAULT_PLUGINS: truthy("AIWORK_ENGINE_DISABLE_DEFAULT_PLUGINS"),
  AIWORK_ENGINE_DISABLE_LSP_DOWNLOAD: truthy("AIWORK_ENGINE_DISABLE_LSP_DOWNLOAD"),
  AIWORK_ENGINE_ENABLE_EXPERIMENTAL_MODELS: truthy("AIWORK_ENGINE_ENABLE_EXPERIMENTAL_MODELS"),
  AIWORK_ENGINE_DISABLE_AUTOCOMPACT: truthy("AIWORK_ENGINE_DISABLE_AUTOCOMPACT"),
  AIWORK_ENGINE_DISABLE_MODELS_FETCH: truthy("AIWORK_ENGINE_DISABLE_MODELS_FETCH"),
  AIWORK_ENGINE_DISABLE_MOUSE: truthy("AIWORK_ENGINE_DISABLE_MOUSE"),
  AIWORK_ENGINE_DISABLE_CLAUDE_CODE,
  AIWORK_ENGINE_DISABLE_CLAUDE_CODE_PROMPT: AIWORK_ENGINE_DISABLE_CLAUDE_CODE || truthy("AIWORK_ENGINE_DISABLE_CLAUDE_CODE_PROMPT"),
  AIWORK_ENGINE_DISABLE_CLAUDE_CODE_SKILLS,
  AIWORK_ENGINE_DISABLE_EXTERNAL_SKILLS: truthy("AIWORK_ENGINE_DISABLE_EXTERNAL_SKILLS"),
  AIWORK_ENGINE_FAKE_VCS: process.env["AIWORK_ENGINE_FAKE_VCS"],
  AIWORK_ENGINE_SERVER_PASSWORD: process.env["AIWORK_ENGINE_SERVER_PASSWORD"],
  AIWORK_ENGINE_SERVER_USERNAME: process.env["AIWORK_ENGINE_SERVER_USERNAME"],
  AIWORK_ENGINE_ENABLE_QUESTION_TOOL: truthy("AIWORK_ENGINE_ENABLE_QUESTION_TOOL"),

  // Experimental
  AIWORK_ENGINE_EXPERIMENTAL,
  AIWORK_ENGINE_EXPERIMENTAL_FILEWATCHER: Config.boolean("AIWORK_ENGINE_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  AIWORK_ENGINE_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("AIWORK_ENGINE_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  AIWORK_ENGINE_EXPERIMENTAL_ICON_DISCOVERY: AIWORK_ENGINE_EXPERIMENTAL || truthy("AIWORK_ENGINE_EXPERIMENTAL_ICON_DISCOVERY"),
  AIWORK_ENGINE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("AIWORK_ENGINE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  AIWORK_ENGINE_ENABLE_EXA: truthy("AIWORK_ENGINE_ENABLE_EXA") || AIWORK_ENGINE_EXPERIMENTAL || truthy("AIWORK_ENGINE_EXPERIMENTAL_EXA"),
  AIWORK_ENGINE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("AIWORK_ENGINE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  AIWORK_ENGINE_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("AIWORK_ENGINE_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  AIWORK_ENGINE_EXPERIMENTAL_OXFMT: AIWORK_ENGINE_EXPERIMENTAL || truthy("AIWORK_ENGINE_EXPERIMENTAL_OXFMT"),
  AIWORK_ENGINE_EXPERIMENTAL_LSP_TY: truthy("AIWORK_ENGINE_EXPERIMENTAL_LSP_TY"),
  AIWORK_ENGINE_EXPERIMENTAL_LSP_TOOL: AIWORK_ENGINE_EXPERIMENTAL || truthy("AIWORK_ENGINE_EXPERIMENTAL_LSP_TOOL"),
  AIWORK_ENGINE_EXPERIMENTAL_PLAN_MODE: AIWORK_ENGINE_EXPERIMENTAL || truthy("AIWORK_ENGINE_EXPERIMENTAL_PLAN_MODE"),
  AIWORK_ENGINE_EXPERIMENTAL_MARKDOWN: !falsy("AIWORK_ENGINE_EXPERIMENTAL_MARKDOWN"),
  AIWORK_ENGINE_MODELS_URL: process.env["AIWORK_ENGINE_MODELS_URL"],
  AIWORK_ENGINE_MODELS_PATH: process.env["AIWORK_ENGINE_MODELS_PATH"],
  AIWORK_ENGINE_DISABLE_EMBEDDED_WEB_UI: truthy("AIWORK_ENGINE_DISABLE_EMBEDDED_WEB_UI"),
  AIWORK_ENGINE_DB: process.env["AIWORK_ENGINE_DB"],
  AIWORK_ENGINE_SKIP_MIGRATIONS: truthy("AIWORK_ENGINE_SKIP_MIGRATIONS"),
  AIWORK_ENGINE_STRICT_CONFIG_DEPS: truthy("AIWORK_ENGINE_STRICT_CONFIG_DEPS"),

  AIWORK_ENGINE_WORKSPACE_ID: process.env["AIWORK_ENGINE_WORKSPACE_ID"],
  // so internal users exercise the
  // new effect-httpapi server backend. Stable (`prod`/`latest`) installs stay
  // on the legacy hono backend until the rollout is complete. An explicit env
  // var ("true"/"1" or "false"/"0") always wins, providing an opt-in for
  // stable users and an escape hatch for dev/beta users.
  AIWORK_ENGINE_EXPERIMENTAL_HTTPAPI:
    truthy("AIWORK_ENGINE_EXPERIMENTAL_HTTPAPI") ,
  AIWORK_ENGINE_EXPERIMENTAL_WORKSPACES: AIWORK_ENGINE_EXPERIMENTAL || truthy("AIWORK_ENGINE_EXPERIMENTAL_WORKSPACES"),
  AIWORK_ENGINE_EXPERIMENTAL_EVENT_SYSTEM: AIWORK_ENGINE_EXPERIMENTAL || truthy("AIWORK_ENGINE_EXPERIMENTAL_EVENT_SYSTEM"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get AIWORK_ENGINE_DISABLE_PROJECT_CONFIG() {
    return truthy("AIWORK_ENGINE_DISABLE_PROJECT_CONFIG")
  },
  get AIWORK_ENGINE_CONFIG_DIR() {
    return process.env["AIWORK_ENGINE_CONFIG_DIR"]
  },
  get AIWORK_ENGINE_PURE() {
    return truthy("AIWORK_ENGINE_PURE")
  },
  get AIWORK_ENGINE_PLUGIN_META_FILE() {
    return process.env["AIWORK_ENGINE_PLUGIN_META_FILE"]
  },
  get AIWORK_ENGINE_CLIENT() {
    return process.env["AIWORK_ENGINE_CLIENT"] ?? "cli"
  },
}
