import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const ENGINE_EXPERIMENTAL = truthy("ENGINE_EXPERIMENTAL")
const ENGINE_DISABLE_CLAUDE_CODE = truthy("ENGINE_DISABLE_CLAUDE_CODE")
const ENGINE_DISABLE_CLAUDE_CODE_SKILLS =
  ENGINE_DISABLE_CLAUDE_CODE || truthy("ENGINE_DISABLE_CLAUDE_CODE_SKILLS")
const copy = process.env["ENGINE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  ENGINE_AUTO_SHARE: truthy("ENGINE_AUTO_SHARE"),
  ENGINE_AUTO_HEAP_SNAPSHOT: truthy("ENGINE_AUTO_HEAP_SNAPSHOT"),
  ENGINE_GIT_BASH_PATH: process.env["ENGINE_GIT_BASH_PATH"],
  ENGINE_CONFIG: process.env["ENGINE_CONFIG"],
  ENGINE_CONFIG_CONTENT: process.env["ENGINE_CONFIG_CONTENT"],
  ENGINE_DISABLE_AUTOUPDATE: truthy("ENGINE_DISABLE_AUTOUPDATE"),
  ENGINE_ALWAYS_NOTIFY_UPDATE: truthy("ENGINE_ALWAYS_NOTIFY_UPDATE"),
  ENGINE_DISABLE_PRUNE: truthy("ENGINE_DISABLE_PRUNE"),
  ENGINE_DISABLE_TERMINAL_TITLE: truthy("ENGINE_DISABLE_TERMINAL_TITLE"),
  ENGINE_SHOW_TTFD: truthy("ENGINE_SHOW_TTFD"),
  ENGINE_PERMISSION: process.env["ENGINE_PERMISSION"],
  ENGINE_DISABLE_DEFAULT_PLUGINS: truthy("ENGINE_DISABLE_DEFAULT_PLUGINS"),
  ENGINE_DISABLE_LSP_DOWNLOAD: truthy("ENGINE_DISABLE_LSP_DOWNLOAD"),
  ENGINE_ENABLE_EXPERIMENTAL_MODELS: truthy("ENGINE_ENABLE_EXPERIMENTAL_MODELS"),
  ENGINE_DISABLE_AUTOCOMPACT: truthy("ENGINE_DISABLE_AUTOCOMPACT"),
  ENGINE_DISABLE_MODELS_FETCH: truthy("ENGINE_DISABLE_MODELS_FETCH"),
  ENGINE_DISABLE_MOUSE: truthy("ENGINE_DISABLE_MOUSE"),
  ENGINE_DISABLE_CLAUDE_CODE,
  ENGINE_DISABLE_CLAUDE_CODE_PROMPT: ENGINE_DISABLE_CLAUDE_CODE || truthy("ENGINE_DISABLE_CLAUDE_CODE_PROMPT"),
  ENGINE_DISABLE_CLAUDE_CODE_SKILLS,
  ENGINE_DISABLE_EXTERNAL_SKILLS: truthy("ENGINE_DISABLE_EXTERNAL_SKILLS"),
  ENGINE_FAKE_VCS: process.env["ENGINE_FAKE_VCS"],
  ENGINE_SERVER_PASSWORD: process.env["ENGINE_SERVER_PASSWORD"],
  ENGINE_SERVER_USERNAME: process.env["ENGINE_SERVER_USERNAME"],
  ENGINE_ENABLE_QUESTION_TOOL: truthy("ENGINE_ENABLE_QUESTION_TOOL"),

  // Experimental
  ENGINE_EXPERIMENTAL,
  ENGINE_EXPERIMENTAL_FILEWATCHER: Config.boolean("ENGINE_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  ENGINE_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("ENGINE_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  ENGINE_EXPERIMENTAL_ICON_DISCOVERY: ENGINE_EXPERIMENTAL || truthy("ENGINE_EXPERIMENTAL_ICON_DISCOVERY"),
  ENGINE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("ENGINE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  ENGINE_ENABLE_EXA: truthy("ENGINE_ENABLE_EXA") || ENGINE_EXPERIMENTAL || truthy("ENGINE_EXPERIMENTAL_EXA"),
  ENGINE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("ENGINE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  ENGINE_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("ENGINE_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  ENGINE_EXPERIMENTAL_OXFMT: ENGINE_EXPERIMENTAL || truthy("ENGINE_EXPERIMENTAL_OXFMT"),
  ENGINE_EXPERIMENTAL_LSP_TY: truthy("ENGINE_EXPERIMENTAL_LSP_TY"),
  ENGINE_EXPERIMENTAL_LSP_TOOL: ENGINE_EXPERIMENTAL || truthy("ENGINE_EXPERIMENTAL_LSP_TOOL"),
  ENGINE_EXPERIMENTAL_PLAN_MODE: ENGINE_EXPERIMENTAL || truthy("ENGINE_EXPERIMENTAL_PLAN_MODE"),
  ENGINE_EXPERIMENTAL_MARKDOWN: !falsy("ENGINE_EXPERIMENTAL_MARKDOWN"),
  ENGINE_MODELS_URL: process.env["ENGINE_MODELS_URL"],
  ENGINE_MODELS_PATH: process.env["ENGINE_MODELS_PATH"],
  ENGINE_DISABLE_EMBEDDED_WEB_UI: truthy("ENGINE_DISABLE_EMBEDDED_WEB_UI"),
  ENGINE_DB: process.env["ENGINE_DB"],
  ENGINE_SKIP_MIGRATIONS: truthy("ENGINE_SKIP_MIGRATIONS"),
  ENGINE_STRICT_CONFIG_DEPS: truthy("ENGINE_STRICT_CONFIG_DEPS"),

  ENGINE_WORKSPACE_ID: process.env["ENGINE_WORKSPACE_ID"],
  // so internal users exercise the
  // new effect-httpapi server backend. Stable (`prod`/`latest`) installs stay
  // on the legacy hono backend until the rollout is complete. An explicit env
  // var ("true"/"1" or "false"/"0") always wins, providing an opt-in for
  // stable users and an escape hatch for dev/beta users.
  ENGINE_EXPERIMENTAL_HTTPAPI:
    truthy("ENGINE_EXPERIMENTAL_HTTPAPI") ,
  ENGINE_EXPERIMENTAL_WORKSPACES: ENGINE_EXPERIMENTAL || truthy("ENGINE_EXPERIMENTAL_WORKSPACES"),
  ENGINE_EXPERIMENTAL_EVENT_SYSTEM: ENGINE_EXPERIMENTAL || truthy("ENGINE_EXPERIMENTAL_EVENT_SYSTEM"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get ENGINE_DISABLE_PROJECT_CONFIG() {
    return truthy("ENGINE_DISABLE_PROJECT_CONFIG")
  },
  get ENGINE_CONFIG_DIR() {
    return process.env["ENGINE_CONFIG_DIR"]
  },
  get ENGINE_PURE() {
    return truthy("ENGINE_PURE")
  },
  get ENGINE_PLUGIN_META_FILE() {
    return process.env["ENGINE_PLUGIN_META_FILE"]
  },
  get ENGINE_CLIENT() {
    return process.env["ENGINE_CLIENT"] ?? "cli"
  },
}
